### ISSUE TITLE
Missing dependency: `react-native-masked-text`

### ISSUE THREAD

**Issue by jackHedaya** [kcotias/react-native-animated-input#11]
I see `react-native-masked-text` used in `AnimatedInput/index.js` but not declared in `package.json`. This is prevents the project from building.

Installation was done using `yarn` perhaps it's a part of the issue?

**Comment by jackHedaya** [comment]
I was able to resolve this issue on my end by adding `"react-native-masked-text": "^1.13.0"` as a dependency for my project. However, I think it makes more sense for this project to include the dependency itself.

**Comment by kcotias** [comment]
Hey man, you're right! Sorry for that! Pushing a new version with the fix :)
