### ISSUE TITLE
Refs

### ISSUE THREAD

**Issue by falay26** [kcotias/react-native-animated-input#5]
I wasn't able to use ref in this library. I was just trying to do focus to the next TextInput. I have tried fowardRef but couldn't make it work. P.S. I also had to add "useNativeDriver: false" line in 87th line in index.js to the rid of the warning from Animated API

**Comment by kcotias** [comment]
Hey! thanks for your feedback! Will check this out asap!

**Comment by kcotias** [comment]
Solved and already published to npm friend! Try out 1.0.2 :)
